services:
  django:
    image: ghcr.io/astral-sh/uv:0.6-python3.13-bookworm-slim
    working_dir: /app
    restart: on-failure
    networks:
      - hacktj_net
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/.venv
    entrypoint:
      - uv
      - run
      - /app/manage.py
      - runserver
      - 0.0.0.0:8080

  next:
    container_name: hacktj25_nextjs
    build:
      dockerfile_inline: |
        FROM node:23-alpine3.20

        ENV PNPM_HOME="/pnpm"
        ENV PATH="$PNPM_HOME:$PATH"

        WORKDIR /app

        COPY hacktj25/pnpm-lock.yaml .
        COPY hacktj25/package.json .

        ENV TZ=America/New_York

        RUN corepack enable
    image: hacktj25_base
    working_dir: /app
    restart: on-failure
    networks:
      - hacktj_net
    ports:
      - 3000:3000
    volumes:
      - ./hacktj25:/app
    entrypoint:
      - sh
      - -c
      - |
        pnpm install
        exec pnpm start

networks:
  hacktj_net:
    driver: bridge
    name: hacktj25_net

volumes:
  hacktj-pgdata:
