[project]
name = "hacktj25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.7",
    "django-fastdev>=1.13.0",
    "djangorestframework>=3.15.2",
]
