# Compose.yaml for BACKEND ONLY
services:
  django:
    image: ghcr.io/astral-sh/uv:0.6-python3.13-bookworm-slim
    working_dir: /app
    restart: on-failure
    networks:
      - credibly_net
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/.venv
    entrypoint:
      - uv
      - run
      - /app/manage.py
      - runserver
      - 0.0.0.0:8080
    environment:
      UV_LINK_MODE: copy

  redis:
    image: redis:latest
    networks:
      - credibly_net
    expose:
      - "6379"

  celery:
    image: ghcr.io/astral-sh/uv:0.6-python3.13-bookworm-slim
    entrypoint:
      - uv
      - run
      - -m
      - watchfiles
      - --filter
      - python
      - "uv run celery -A credibly worker"
      - /app/credibly/apps
    working_dir: /app
    networks:
      - credibly_net
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - redis
    environment:
      UV_LINK_MODE: copy

networks:
  credibly_net:
    driver: bridge
    name: credibly_net

volumes:
  credibly-pgdata:
